### ISSUE TITLE
OB-0002: Adicionar busca por OAs pela PCN

### ISSUE THREAD

**Issue by vitorhenriquec** [obama-imd/obama#17]
**Eu enquanto** OBAMA
**Gostaria qu**e a aplicação tenha uma rota que retorne uma lista ordenada por nome de Objetos de Aprendizagems(OA)s considerando a avaliação da PCN
Para que o usuário consiga achar o OA de sua preferência

**Descrição**

O objetivo dessa taks é  reimplementar a feature de busca por Objetos de Aprendizagem pela PCN. Essa busca sempre retornará uma lista ordenada pelo nome dos objetos de aprendizagem e terá que ser paginada. Ela irá levar em consideração os seguintes parâmetros:

- Nome do Objeto de Aprendizagem;
- Curriculo;
- Tipo de Acesso;
- Nivel de Ensino;
- Tema Curricular;
- Descritor.
- Eles podem ou não estar inseridos na requisição.

Caso tenha objetos de aprendizagem dados os parâmetros da requisição a resposta precisa ser:

**Critérios de Aceite**

- Teste de componente na aplicação;
- Teste de integração na aplicação;
- Possibilidade de interação com swagger funcionando;
- Criação de índices se necessário.
- 

**Riscos**

N/A
**Dependências**

N/A

**Comment by Kywal** [comment]
PCN -> descritores
BNCC -> habilidades
