### ISSUE TITLE
OB-0017: Altera componente depreciado PropertyNamingStrategy.SnakeCaseStrategy

### ISSUE THREAD

**Issue by vitorhenriquec** [obama-imd/obama#42]
**Descrição do bug**

O objetivo dessa task é altera o componente depreciado PropertyNamingStrategy.SnakeCaseStrategy para uma versão não depreciada

**O que é esperado**

- A aplicação continue funcionando normalmente
- Todos testes continue funcionando

**Comment by Kywal** [comment]
Concluído em #43
