### ISSUE TITLE
OB-0018: Salvar um novo plano de aula

### ISSUE THREAD

**Issue by vitorhenriquec** [obama-imd/obama#47]
**Eu** enquanto OBAMA
**Gostaria que** usuário pudesse salvar um novo plano
**Para que** salvar os planos das suas aulas

**Descrição**

O objetivo dessa tarefa é que um usuário consiga criar um plano de aula. Para isso é necessário que:
- Exista uma rota POST na aplicação responsável por salvar os planos de aula de um usuário
- A rota deve exigir as seguintes informações no corpo da requisição:
  - escola (pode ser nulo)
  - o id do nivel de ensino(pode ser nulo)
  - uma lista de ids de disciplina envolvidas (pode ser uma lista vazia)
  - o id  do ano de ensino (pode ser nulo)
  - valor númerico que represente a duracao em minutos da execução do plano (pode ser nulo)
  - texto com o titulo do plano (pode ser nulo)
  - texto com a metodologia (pode ser nulo)
  - texto com os objetivos específicos (pode ser nulo)
  - texto com o objetivo geral (pode ser nulo)
  - texto com a avaliação (pode ser nulo)
  - texto com a referência (pode ser nulo)
- A rota deve retornar **400** caso:
  - O id do nível ensino seja informado e seja uma inválido
  - A duração em minutos seja informada e ela seja menor do que 0
  - algum dos ids da lista de ids das disciplinas envolvidas seja inválido
  - id do ano de ensino seja informado e seja uma inválido
- A rota deve retornar **201** com o id do plano de aula no corpo da requisição caso e plano de aula deve ser salvo com status **RASCUNHO** no banco e deve salvar o título com o valor **Plano sem título**.
- Essa rota só pode ser usado se o usuário é autenticado caso contrário deve responder 403.

**Critérios de Aceite**

- Testes na aplicação;
- Possibilidade de interação com swagger funcionando;
- Criação de índices se necessário.
- Qualquer tipo de usuário possa criar o plano de aula.
- Usar padrão **snake_case** no retorno dos objetos.

**Riscos e Dependências**
- Dependências:
  - OB-0023 [#54]
  - OB-0028 [#64]
  - OB-0029 [#65]

**Comment by Kywal** [comment]
@vitorhenriquec 

Não entendi muito bem quando o plano de aula tem que ser salvo como rascunho. É somente quando a requisição não possuir título do plano?
